Password Vault/auth/urls.py
from django.urls import path
from .views import AuthLoginView, logoutView, RegisterView

urlpatterns = [
    path('login/', AuthLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout', logoutView, name="logout")
]

Password Vault/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('auth.urls', 'auth'), namespace='auth')),
    path('management/', include(('management.urls',
        'management'), namespace='management')),
    path('', include(('home.urls', 'home'), namespace='home'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Password Vault/home/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home/index.html"), name='index')
]

Password Vault/management/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    ManagementListView,
    ManagementCreateView,
    ManagementUpdateView,
    ManagementDeleteView
)

urlpatterns = [
    path('update/<int:pk>/',
         login_required(ManagementUpdateView.as_view()), name='update'),
    path('delete/<int:pk>/',
         login_required(ManagementDeleteView.as_view()), name='delete'),
    path('list/',
         login_required(ManagementListView.as_view(template_name="management/list.html")), name='list'),
    path('create/',
         login_required(ManagementCreateView.as_view()), name='create'),
    path('manage/',
         login_required(ManagementListView.as_view(template_name="management/manage.html")), name='manage'),
]

Password Vault/home/models.py
from django.db import models

Password Vault/management/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import base64
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from django.conf import settings
import os

def get_encryption_key(user_id):
    """Generate a unique encryption key based on user_id and SECRET_KEY"""
    salt = str(user_id).encode()
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=100000,
    )
    key = base64.urlsafe_b64encode(kdf.derive(settings.SECRET_KEY.encode()))
    return key

class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image_site = models.ImageField(
        upload_to="images", default="images/default.png", blank=True)
    site_name = models.URLField(max_length=255)
    email = models.EmailField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    
    def encrypt_password(self, raw_password):
        """Encrypt the password before saving"""
        key = get_encryption_key(self.user_id)
        fernet = Fernet(key)
        return fernet.encrypt(raw_password.encode()).decode()
    
    def decrypt_password(self):
        """Decrypt the stored password"""
        key = get_encryption_key(self.user_id)
        fernet = Fernet(key)
        return fernet.decrypt(self.password.encode()).decode()
    
    def save(self, *args, **kwargs):
        # Only encrypt if this is a new record or password changed and isn't already encrypted
        if not self.pk or kwargs.pop('password_changed', False):
            try:
                # Try to decrypt - if it works, it's already encrypted
                self.decrypt_password()
            except:
                # If decryption fails, it's not encrypted yet
                self.password = self.encrypt_password(self.password)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('management:list')

    def __str__(self):
        return self.site_name

Password Vault/management/forms.py
from django import forms
from .models import Account


class ManagementCreateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['image_site', 'site_name', 'email', 'username', 'password']
        widgets = {
            'site_name': forms.TextInput(attrs={'placeholder': 'Site name'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'password': forms.TextInput(attrs={'placeholder': 'password'}),
        }

Password Vault/home/views.py
from django.shortcuts import render

Password Vault/management/views.py
from django.http import request
from django.utils.datastructures import MultiValueDict, MultiValueDictKeyError
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Account
from .forms import ManagementCreateForm


class ManagementListView(ListView):
    model = Account
    ordering = ('-id',)
    paginate_by = 6
    context_object_name = 'accounts'

    def get_queryset(self):
        try:
            search = self.request.GET['search']
            return self.model.objects.filter(site_name__icontains=search, user=self.request.user)
        except MultiValueDictKeyError:
            return self.model.objects.filter(user=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Decrypt passwords for display
        for account in context['accounts']:
            # Add decrypted password as property for use in templates
            account.decrypted_password = account.decrypt_password()
        return context


class ManagementCreateView(CreateView):
    form_class = ManagementCreateForm
    template_name = 'management/create.html'
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ManagementUpdateView(UpdateView):
    model = Account
    fields = ['image_site', 'site_name', 'email', 'username', 'password']
    template_name = 'management/update.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'img_url': self.get_object().image_site.url})
        return context
    
    def form_valid(self, form):
        # Check if password was changed
        if self.get_object().password != form.cleaned_data['password']:
            # Set flag to indicate password needs re-encryption
            form.instance.password_changed = True
        return super().form_valid(form)
    
    def get_queryset(self):
        # Ensure users can only update their own accounts
        return self.model.objects.filter(user=self.request.user)


class ManagementDeleteView(DeleteView):
    model = Account
    template_name = 'management/delete_confirm.html'
    success_url = reverse_lazy('management:manage')
    
    def get_queryset(self):
        # Ensure users can only delete their own accounts
        return self.model.objects.filter(user=self.request.user)

Password Vault/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Password Manager{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/main.css' %}" />
  </head>
  <body>
    {% if request.user.is_authenticated %}
    <div class="logout-btn" title="Logout">
      <a href="{% url 'auth:logout' %}">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
          />
        </svg>
      </a>
    </div>
    {% endif %} {% block content %}
    <!-- MAIN CONTENT GOES HERE -->
    {% endblock content %}
  </body>
</html>

Password Vault/home/templates/home/index.html
{% extends 'home/base.html' %} {% load static %}

<!-- PAGE TITLE -->
{% block title %}{{ block.super }} | Home{% endblock title %}

<!-- MAIN CONTENT -->
{% block content %}
<div class="home">
  <div class="hero">
    <div class="left-content">
      <h1 class="title-page">password manager</h1>
      <p class="desc-title">Save your social media account password here, so you don't forget it</p>
      {% if request.user.is_authenticated %}
      <a href="{% url 'management:list' %}" class="btn">Show All</a>
      {% else %}
      <a href="{% url 'auth:login' %}" class="btn">Login</a>
      {% endif %}
    </div>
    <img src="{% static 'home/images/lock.svg' %}" alt="password secure image" />
  </div>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" class="wave">
    <path
      fill="#101820"
      fill-opacity="1"
      d="M0,64L48,101.3C96,139,192,213,288,224C384,235,480,181,576,170.7C672,160,768,192,864,192C960,192,1056,160,1152,160C1248,160,1344,192,1392,208L1440,224L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"
    ></path>
  </svg>
</div>
{% endblock content %}

Password Vault/management/templates/management/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Management{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'management/css/main.css' %}" />
  </head>
  <body>
    <div class="logout-btn" title="Logout">
      <a href="{% url 'auth:logout' %}">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
          />
        </svg>
      </a>
    </div>
    {% block content %}
    <!-- MAIN CONTENT GOES HERE -->
    {% endblock content %}
    <script src="{% static 'management/js/password-toggle.js' %}"></script>
    {% block js %} {% endblock js %}
  </body>
</html>

Password Vault/management/templates/management/create.html
{% extends 'management/base.html' %} {% load static %}

<!-- PAGE TITLE -->
{% block title %}{{ block.super }} | Create{% endblock title %}

<!-- MAIN CONTENT -->
{% block content %}
<div class="management">
  <header>
    <div class="left-content">
      <img src="{% static 'management/images/create.svg' %}" alt="the illustration image" />
    </div>
    <div class="right-content">
      <h1 class="title-page">Create Your New Account List</h1>
      <div class="action">
        <a href="{% url 'management:list' %}" class="btn">Show All</a>
        <a href="{% url 'management:manage' %}" class="btn">Manage</a>
      </div>
    </div>
  </header>

  <div class="create-form">
    <form id="create-form" method="POST" enctype="multipart/form-data">
      {% csrf_token %} {% for field in form %}{{field}}
      <!-- SHOW ERROR -->
      {{field.errors}} {% endfor %}
      <button type="submit" class="btn btn-white btn-sm">Create</button>
    </form>
  </div>
</div>
{% endblock content %}

Password Vault/management/templates/management/delete_confirm.html
{% extends 'management/base.html' %}

<!-- PAGE TITLE -->
{% block title %}{{ block.super }} | Delete{% endblock title %}

<!-- MAIN CONTENT -->
{% block content %}
<div class="delete-confirm">
  <div class="card-delete">
    <h1>Delete Account</h1>
    <p>Are you sure you want to delete the account information related to <a href="#">{{account.site_name}}</a></p>
    <a href="{% url 'management:manage' %}" class="btn btn-white btn-sm">Cancel</a>
    <form method="post" style="display: inline-block">
      {% csrf_token %}
      <button type="submit" class="btn btn-delete btn-sm">Confirm</button>
    </form>
  </div>
</div>
{% endblock content %}

Password Vault/management/templates/management/list.html
{% extends 'management/base.html' %} {% load static %}

<!-- TITLE PAGE -->
{% block title %}{{ block.super }} | List{% endblock title %}

<!-- MAIN CONTENT -->
{% block content %}
<div class="management">
  <header>
    <div class="left-content">
      <img src="{% static 'management/images/list.svg' %}" alt="the illustration image" />
    </div>
    <div class="right-content">
      <h1 class="title-page">Your Account and Password List</h1>
      <div class="action">
        <a href="{% url 'management:create' %}" class="btn">Create New</a>
        <a href="{% url 'management:manage' %}" class="btn">Manage</a>
      </div>
      {% include 'management/partials/form-search.html' with isList=True %}
    </div>
  </header>

  <div class="list-card">
    {% if accounts|length > 0 %}
      {% for account in accounts %}
      <!-- include card content -->
      {% include 'management/partials/card.html' with img_url=account.image_site.url site_name=account.site_name username=account.username email=account.email decrypted_password=account.decrypted_password %}
      {% endfor %}
    {% else %}
      {% include 'no-data-found.html' %}
    {% endif %}
  </div>
  
  {% include 'pagination.html' %}
</div>


<!-- JAVASCRIPT -->
<script src="{% static 'management/js/list.js' %}"></script>
{% endblock content %}

Password Vault/management/templates/management/manage.html
{% extends 'management/base.html' %} {% load static %}

<!-- TITLE PAGE -->
{% block title %}{{ block.super }} | Manage{% endblock title %}

<!-- MAIN CONTENT -->
{% block content %}
<div class="management">
  <header>
    <div class="left-content">
      <img src="{% static 'management/images/manage.svg' %}" alt="the illustration image" />
    </div>
    <div class="right-content">
      <h1 class="title-page">Manage Your Account List</h1>
      <div class="action">
        <a href="{% url 'management:list' %}" class="btn">Show All</a>
        <a href="{% url 'management:create' %}" class="btn">Create New</a>
      </div>
      {% include 'management/partials/form-search.html' %}
    </div>
  </header>

  <div class="manage-content">
    {% if accounts|length > 0 %}
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Site Name</th>
          <th>Email</th>
          <th>Username</th>
          <th>Password</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for account in accounts %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td><a class="link" href="{{account.site_name}}" target="_blank">{{account.site_name}}</a></td>
          <td>{{account.email}}</td>
          <td>{{account.username}}</td>
          <td class="password-cell">
            <span class="password-hidden">••••••••••</span>
            <span class="password-visible" style="display: none;">{{account.decrypted_password}}</span>
            <button class="toggle-password-btn" title="Toggle visibility">
              <svg xmlns="http://www.w3.org/2000/svg" class="eye-icon" width="16" height="16" viewBox="0 0 20 20" fill="currentColor">
                <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
                <path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd" />
              </svg>
              <svg xmlns="http://www.w3.org/2000/svg" class="eye-off-icon" width="16" height="16" viewBox="0 0 20 20" fill="currentColor" style="display: none;">
                <path fill-rule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z" clip-rule="evenodd" />
                <path d="M12.454 16.697L9.75 13.992a4 4 0 01-3.742-3.741L2.335 6.578A9.98 9.98 0 00.458 10c1.274 4.057 5.065 7 9.542 7 .847 0 1.669-.105 2.454-.303z" />
              </svg>
            </button>
          </td>
          <td class="btn-action">
            <a href="{% url 'management:update' account.id %}" class="btn btn-badge btn-edit">Edit</a>
            <a href="{% url 'management:delete' account.id %}" class="btn btn-badge btn-delete">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %} {% include 'no-data-found.html' %} {% endif %}
  </div>

  {% include 'pagination.html' %}
</div>
{% endblock content %}

Password Vault/management/templates/management/partials/card.html
<div class="card">
  <div class="card-heading">
    <div class="image-site">
      <img src="{{img_url}}" alt="{{site_name}}" loading='lazy' />
    </div>
    <div class="site">
      <a href="{{site_name}}" target="_blank">{{site_name}}</a>
    </div>
  </div>
  <div class="card-content">
    <div class="username wrapper">
      <h5>{{username}}</h5>
      <div title="copy" data-content="{{username}}" class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
          <path d="M8 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" />
          <path d="M6 3a2 2 0 00-2 2v11a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2 3 3 0 01-3 3H9a3 3 0 01-3-3z" />
        </svg>
      </div>
    </div>
    <div class="email wrapper">
      <h5>{{email}}</h5>
      <div title="copy" data-content="{{email}}" class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
          <path d="M8 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" />
          <path d="M6 3a2 2 0 00-2 2v11a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2a3 3 0 01-3 3H9a3 3 0 01-3-3z" />
        </svg>
      </div>
    </div>
    <div class="password wrapper">
      <h5 class="password-text">
        <span class="password-hidden">••••••••••</span>
        <span class="password-visible" style="display: none;">{{decrypted_password}}</span>
      </h5>
      <div class="action-icons">
        <div title="toggle visibility" class="icon toggle-password">
          <svg xmlns="http://www.w3.org/2000/svg" class="eye-icon" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
            <path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd" />
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" class="eye-off-icon" viewBox="0 0 20 20" fill="currentColor" style="display: none;">
            <path fill-rule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z" clip-rule="evenodd" />
            <path d="M12.454 16.697L9.75 13.992a4 4 0 01-3.742-3.741L2.335 6.578A9.98 9.98 0 00.458 10c1.274 4.057 5.065 7 9.542 7 .847 0 1.669-.105 2.454-.303z" />
          </svg>
        </div>
        <div title="copy" data-content="{{decrypted_password}}" class="icon">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path d="M8 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" />
            <path d="M6 3a2 2 0 00-2 2v11a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2 3 3 0 01-3 3H9a3 3 0 01-3-3z" />
          </svg>
        </div>
      </div>
    </div>
  </div>
</div>

Password Vault/management/templates/management/partials/form-search.html
<form id="list-form">
  <div class="main">
    <input type="text" name="search" id="search" placeholder="Search by site name" required />
    <button class="btn btn-sm btn-white">Search</button>
  </div>
  {% if request.GET.search %}
  <a href="{% if isList %}{% url 'management:list' %}{% else %}{% url 'management:manage' %}{% endif %}" class="btn btn-sm btn-all-list">All</a>
  {% endif %}
</form>

Password Vault/management/templates/management/partials/header.html
{% load static %}

Password Vault/management/templates/management/update.html
{% extends 'management/base.html' %} {% load static %}

<!-- PAGE TITLE -->
{% block title %}{{ block.super }} | Create{% endblock title %}

<!-- MAIN CONTENT -->
{% block content %}
<div class="management">
  <header>
    <div class="left-content">
      <img src="{% static 'management/images/update.svg' %}" alt="the illustration image" />
    </div>
    <div class="right-content">
      <h1 class="title-page">Update Your Account In Here</h1>
      <div class="action">
        <a href="{% url 'management:list' %}" class="btn">Show All</a>
        <a href="{% url 'management:manage' %}" class="btn">Manage</a>
      </div>
    </div>
  </header>

  <div class="create-form">
    <form id="create-form" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- RENDER FILE IMAGE FIELD -->
      <input type="file" name="image_site" accept="image/*" />
      <div class="current-image">
        <small>Current: <a href="{{img_url}}" target="_blank">{{img_url}}</a></small>
      </div>
      <!-- RENDER FIELDS EXCLUDE TYPE FILE -->
      {% for field in form %} {% if field.html_name != 'image_site' %}{{field}}{% endif %} {% endfor %}
      <button type="submit" class="btn btn-white btn-sm">Update</button>
    </form>
  </div>
</div>
{% endblock content %}

Password Vault/templates/no-data-found.html
{% load static %}

<div class="no-data-found">
  <img src="{% static 'images/no-data-found.svg' %}" alt="" />
  <h1>Sad!</h1>
  <h2>No Data Found</h2>
</div>

Password Vault/templates/pagination.html
{% if is_paginated %}
<div class="pagination">
  <div class="page-link">

    {% if page_obj.has_previous %}
    <a href="?page={{page_obj.previous_page_number}}" class="prev btn">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path
          fill-rule="evenodd"
          d="M15.707 15.707a1 1 0 01-1.414 0l-5-5a1 1 0 010-1.414l5-5a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 010 1.414zm-6 0a1 1 0 01-1.414 0l-5-5a1 1 0 010-1.414l5-5a1 1 0 011.414 1.414L5.414 10l4.293 4.293a1 1 0 010 1.414z"
          clip-rule="evenodd"
        />
      </svg>
    </a>
    {% endif %}
   
    {% for i in paginator.page_range %} {% if page_obj.number == i %}
    <a href="?page={{i}}" class="btn btn-white active">{{i}}</a>
    {% else %}
    <a href="?page={{i}}" class="btn btn-num">{{i}}</a>
    {% endif %} {% endfor %}
    
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}" class="next btn">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path
          fill-rule="evenodd"
          d="M10.293 15.707a1 1 0 010-1.414L14.586 10l-4.293-4.293a1 1 0 111.414-1.414l5 5a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0z"
          clip-rule="evenodd"
        />
        <path
          fill-rule="evenodd"
          d="M4.293 15.707a1 1 0 010-1.414L8.586 10 4.293 5.707a1 1 0 011.414-1.414l5 5a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0z"
          clip-rule="evenodd"
        />
      </svg>
    </a>
    {% endif %}
  </div>
</div>
{% endif %}